-- MySQL Script generated by MySQL Workbench
-- sex 26 fev 2021 11:04:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical_exams
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medical_exams` ;

-- -----------------------------------------------------
-- Schema medical_exams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_exams` ;
USE `medical_exams` ;

-- -----------------------------------------------------
-- Table `medical_exams`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_exams`.`patient` ;

CREATE TABLE IF NOT EXISTS `medical_exams`.`patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `process_number` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `addresss` VARCHAR(250) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_exams`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_exams`.`requests` ;

CREATE TABLE IF NOT EXISTS `medical_exams`.`requests` (
  `number` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `patient_id` INT NOT NULL,
  `episode_number` INT NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `fk_requests_1_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_requests_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `medical_exams`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
