-- MySQL Script generated by MySQL Workbench
-- sáb 06 mar 2021 13:58:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical_work_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medical_work_list` ;

-- -----------------------------------------------------
-- Schema medical_work_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_work_list` ;
USE `medical_work_list` ;

-- -----------------------------------------------------
-- Table `medical_work_list`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_work_list`.`patient` ;

CREATE TABLE IF NOT EXISTS `medical_work_list`.`patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `patient_number` INT NOT NULL,
  `patient_name` VARCHAR(100) NULL,
  `patient_address` VARCHAR(250) NULL,
  `patient_phone_number` VARCHAR(15) NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `number_UNIQUE` (`patient_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medical_work_list`.`work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_work_list`.`work` ;

CREATE TABLE IF NOT EXISTS `medical_work_list`.`work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `hour` TIME NOT NULL,
  `request_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `episode_number` INT NOT NULL,
  `report` LONGTEXT NULL,
  `status` VARCHAR(100) NOT NULL DEFAULT 'to be executed',
  `info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_1_idx` (`patient_id` ASC) VISIBLE,
  UNIQUE INDEX `request_id_UNIQUE` (`request_id` ASC) VISIBLE,
  UNIQUE INDEX `patient_id_UNIQUE` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `medical_work_list`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
